/select.do=user.command.UserSelectHandler
/insert.do=user.command.UserInsertHandler
/delete.do=user.command.UserDeleteHandler
/update.do=user.command.UserUpdateHandler
/adminForm.do=user.command.UserAdminFormHandler
/registerForm.do=user.command.UserRegisterFormHandler
/updateForm.do=user.command.UserUpdateFormHandler
/fire.do=user.command.UserFireHandler