/mypage.do=myPage.command.MypageHandler
/mypageEditForm.do=myPage.command.MypageEditFormHandler
/mypageEditPro.do=myPage.command.MypageEditProHandler
/pwUpdatePro.do = myPage.command.PwUpdateProHandler
/pwUpdatePro.do=myPage.command.PwUpdateProHandler
/login.do=user.command.LoginHandler
/main.do=user.command.MainHandler
/logout.do=user.command.LogoutHandler

