#login
/login.do=user.command.LoginHandler
/main.do=user.command.MainHandler
/logout.do=user.command.LogoutHandler

#mypage
/mypage.do=myPage.command.MypageHandler
/mypageEditForm.do=myPage.command.MypageEditFormHandler
/mypageEditPro.do=myPage.command.MypageEditProHandler
/pwUpdatePro.do=myPage.command.PwUpdateProHandler
/myInfo.do=myPage.command.MypageHandler

#contacts
/contactList.do=contacts.command.ContactsController