/login.do=user.command.LoginHandler
/main.do=user.command.MainHandler
/logout.do=user.command.LogoutHandler
/paidleave/write.do=paidLeave.command.WritePaidLeaveHandler
/paidleave.do=paidLeave.command.ListPaidLeaveHandler
/paidleave/read.do=paidLeave.command.ReadPaidLeaveHandler
/paidleave/status.do=paidLeave.command.PaidLeaveStatusHandler